plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.chaquo.python'
}

android {
    namespace 'com.nieche.emu'
    compileSdk 34

    defaultConfig {
        applicationId "com.nieche.emu"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "0.1"
        ndk {

            abiFilters "arm64-v8a", "armeabi-v7a"
        }
        python {
            version "3.11"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }

    packagingOptions { jniLibs { useLegacyPackaging = true } }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
